### ISSUE TITLE
Add notes on how to use with Postgres

### ISSUE THREAD

**Issue by joelclermont** [NoCompromises/laravel-project-standard#14]
php docker file requires `apk libpq-dev` and `docker-php-ext pdo_pgsql`

changes to Docker file

```
postgres:
    container_name: "${COMPOSE_PROJECT_NAME}-postgres"
    image: postgres:15.2-alpine
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app
    ports:
      - "${DOCKER_POSTGRES_LOCAL_PORT}:5432"
    restart: unless-stopped

postgres-test:
    container_name: "${COMPOSE_PROJECT_NAME}-postgres-test"
    image: postgres:15.2-alpine
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=app-test
    restart: unless-stopped

volumes:
  postgres-data:
  postgres-test-data:
```
